import React from 'react';
import styles from './UseCases.module.css';
import { UseCase } from './UseCase';
import { Flash, Refresh01, Globe02, LayersTwo } from 'synthline/react';

export const UseCases: React.FC = () => {
  return (
    <section id="usecases" className={styles.section} aria-labelledby="usecases-title">
      <div className={styles.header}>
        <span className={styles.label}>// CAPABILITIES &amp; USE CASES</span>
        <h2 id="usecases-title" className={styles.title}>
          Engineered for Real-World Product Scenarios
        </h2>
        <p className={styles.description}>
          Explore how teams use Lemmo to accelerate product delivery from days of wireframing 
          down to minutes of automated token synthesis.
        </p>
      </div>

      <div className={styles.useCasesList}>
        <UseCase
          number="01"
          title="Rapid MVP Prototyping"
          description="Transform product requirement documents into functional, responsive web apps. Spin up interactive customer journeys, authentication flows, and data tables with zero scaffolding."
          placeholderId="usecase-01"
          tags={['MVP', 'RapidPrototyping', 'ProductVelocity']}
          type="canvas"
          icon={<Flash size={22} strokeWidth={1.5} />}
        />

        <UseCase
          number="02"
          title="Design-to-Code System Synchronization"
          description="Eliminate the handoff gap. Every component generated by Lemmo is backed by the exact same single-source CSS variables governing your design system."
          placeholderId="usecase-02"
          tags={['DesignTokens', 'SingleSourceOfTruth', 'DesignEngineering']}
          type="interactive"
          icon={<Refresh01 size={22} strokeWidth={1.5} />}
        />

        <UseCase
          number="03"
          title="Multi-Theme & Bilingual Layouts"
          description="Preview your product across Dark, Light, Neon, and Midnight presets with automatic font switching between English (Satoshi/Oddval) and Persian (IRANSans/Morabba)."
          placeholderId="usecase-03"
          tags={['MultiTheme', 'Internationalization', 'RTLReady']}
          type="canvas"
          icon={<Globe02 size={22} strokeWidth={1.5} />}
        />

        <UseCase
          number="04"
          title="Production Micro-Interactions & A11y"
          description="Get keyboard-navigable dialogs, animated switches, and WCAG 2.1 AA compliant color contracts out of the box. No manual contrast fixes required."
          placeholderId="usecase-04"
          tags={['Accessibility', 'WCAG-AA', 'MicroInteractions']}
          type="video"
          icon={<LayersTwo size={22} strokeWidth={1.5} />}
        />
      </div>
    </section>
  );
};
